<?php

namespace Opencontent\OpenApi\OperationFactory\Tags;

use erasys\OpenApi\Spec\v3 as OA;
use ezpRestMvcResult;
use Opencontent\OpenApi\EndpointFactory;
use Opencontent\OpenApi\EndpointFactory\ChildEndpointFactoryInterface;
use Opencontent\OpenApi\EndpointFactory\ChildEndpointFactoryTrait;
use Opencontent\OpenApi\Exceptions\InvalidParameterException;
use Opencontent\OpenApi\Exceptions\NotFoundException;
use Opencontent\OpenApi\OperationFactory\CacheAwareInterface;

class ChildrenOperationFactory extends ListOperationFactory implements ChildEndpointFactoryInterface,
                                                                       CacheAwareInterface
{
    use ChildEndpointFactoryTrait;

    public function setResponseHeaders(EndpointFactory $endpointFactory, ezpRestMvcResult $result): void
    {
        header("Cache-Control: public, must-revalidate, max-age=600, s-maxage=600"); //@todo make configurable
        header("X-Cache-Tags: tags");
        header("Vary: Accept-Language");
    }

    public function hasResponseHeaders(EndpointFactory $endpointFactory, ezpRestMvcResult $result): bool
    {
        return true;
    }

    public function handleCurrentRequest(EndpointFactory $endpointFactory)
    {
        return parent::handleCurrentRequest($endpointFactory); // TODO: Change the autogenerated stub
    }

    /**
     * @throws InvalidParameterException
     * @throws NotFoundException
     */
    protected function getCurrentRequestParameters(): array
    {
        $parameters = parent::getCurrentRequestParameters();
        $requestId = $this->getCurrentRequestParameter($this->getItemIdLabel());
        if (empty($requestId)) {
            throw new InvalidParameterException($this->getItemIdLabel(), $requestId);
        }
        $parameters['parent_remote_id'] = $requestId;

        return $parameters;
    }

    protected function generateOperationAdditionalProperties()
    {
        $properties = parent::generateOperationAdditionalProperties();
        $properties['parameters'] = [
                new OA\Parameter($this->getItemIdLabel(), OA\Parameter::IN_PATH, $this->getItemIdDescription(), [
                    'schema' => $this->generateSchemaProperty(['type' => 'string']),
                    'required' => true,
                ]),
            ] + $properties['parameters'];
        return $properties;
    }
}