<?php

namespace Opencontent\OpenApi\SchemaFactory;

use erasys\OpenApi\Spec\v3 as OA;
use Exception;
use Opencontent\OpenApi\SchemaFactory;

class ApiStatusSchemaFactory extends SchemaFactory
{
    protected $name = 'ApiStatus';

    public function generateSchema()
    {
        $schema = new OA\Schema();
        $schema->title = $this->name;
        $schema->type = 'object';
        $schema->properties = [
            'status' => $this->generateSchemaProperty([
                'type' => 'integer',
                'format' => 'int32',
                'description' => 'The HTTP status code generated by the origin server for this occurrence of the problem.',
                'minimum' => 100,
                'maximum' => 599,
            ]),
        ];

        return $schema;
    }

    public function generateRequestBody()
    {
        return new OA\RequestBody(['application/json' => new OA\MediaType([
            'schema' => new OA\Reference('#/components/schemas/' . $this->name)
        ])]);
    }

    public function serialize()
    {
        return serialize([
            'name' => $this->name,
        ]);
    }
}